mqtt:
  host: "ip"
  port: 1883                 # default 1883
  client_id: "mqtt-cmd"      # default "mqtt-cmd"

templates:
  prepared_command:
    command:
      shell: true
      args: 'echo hello world {{ extra_args | default("") }}'


topics:
  - 'my/topic':
      load_json: true        # default false
      jq_query: ".button"    # optional, applies only to patterns
      #jinja_query: ""       # optional, mutually exclusive with jq_query

      patterns:
        'KEY_PLAY':
          - request:
              method: GET
              url: "https://my_callback.com/?val={{ value['button'] }}"
              #post_data: '' # template string, default none (do not send an HTTP payload)
              #headers: {}   # replace headers, parsed as template strings
              #timeout: 60   # default 60 seconds for request
              #log_response: false  # whether the response should be logged, default false

          - command:
              shell: false   # default false
              args: ['echo', 'lol {{ value }}']
              stdin: null    # default null, can be a string
              #timeout: 5    # default 5 seconds for command

        'KEY_FULL_SCREEN':
          - command:
              shell: true
              args: 'swaymsg fullscreen toggle'

          - template:
              name: prepared_command
              extra_args: "lol"


